{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "triptrace.fullname" . }}-data
  labels:
    app: {{ include "triptrace.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "triptrace.fullname" . }}-uploads
  labels:
    app: {{ include "triptrace.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
{{- end }}
